import globals from 'globals'
import pluginESx from 'eslint-plugin-es-x'
import { createTypeScriptImportResolver } from 'eslint-import-resolver-typescript'

/** @type {import("eslint").Linter.Config[]} */
export default [
    pluginESx.configs['flat/no-new-in-esnext'],
    {
        name: 'jwalker:common',
        linterOptions: { reportUnusedDisableDirectives: true },
        settings: {
            'import-x/resolver-next': [
                createTypeScriptImportResolver(),
            ],
        },
        languageOptions: {
            sourceType: 'module',
            ecmaVersion: 'latest',
            parserOptions: {
                sourceType: 'module',
                ecmaVersion: 'latest',
                ecmaFeatures: {
                    globalReturn: false,
                    impliedStrict: true,
                },
            },
            globals: {
                ...globals.browser,
                ...globals.es2021,
                ...globals.node,
                window: 'readonly',
                document: 'readonly',
                navigator: 'readonly',
            },
        },
        rules: {
            'no-new': 'error',
            'no-var': 'error',
            'no-eval': 'error',
            'no-with': 'error',
            'no-alert': 'error',
            'no-octal': 'error',
            'no-proto': 'error',
            'no-undef': 'error',
            'sort-vars': 'error',
            // best practices ?
            'no-labels': 'error',
            'no-caller': 'error',
            'no-eq-null': 'error',
            'complexity': [1, 20],
            'no-debugger': 'error',
            'no-iterator': 'error',
            'no-new-func': 'error',
            'vars-on-top': 'error',
            'no-undefined': 'error',
            'no-div-regex': 'error',
            'no-dupe-args': 'error',
            'no-dupe-keys': 'error',
            'no-ex-assign': 'error',
            'no-multi-str': 'error',
            'no-obj-calls': 'error',

            'no-sequences': 'error',
            'require-await': 'error',
            'no-delete-var': 'error',
            'no-extra-bind': 'error',
            'no-new-symbol': 'error',
            'no-undef-init': 'error',
            'prefer-spread': 'error',
            'max-depth': ['error', 4],
            'accessor-pairs': 'error',
            'no-fallthrough': 'error',
            'no-func-assign': 'error',
            'no-lone-blocks': 'error',
            'no-unreachable': 'error',
            'max-params': ['error', 3],
            'no-useless-call': 'error',
            'no-class-assign': 'error',
            'no-const-assign': 'error',
            'no-implied-eval': 'error',
            'no-new-wrappers': 'error',
            'no-octal-escape': 'error',

            'no-regex-spaces': 'error',

            'no-self-compare': 'error',

            'prefer-template': 'error',
            'yoda': ['error', 'never'],
            'no-setter-return': 'error',
            'block-scoped-var': 'error',
            'no-control-regex': 'error',
            'no-empty-pattern': 'error',
            'no-extend-native': 'error',
            'no-global-assign': 'error',
            'no-import-assign': 'error',
            'no-sparse-arrays': 'error',
            'no-throw-literal': 'error',
            'no-useless-catch': 'error',
            'no-empty-function': 'error',
            'constructor-super': 'error',
            'default-case-last': 'error',
            'eqeqeq': ['error', 'smart'],
            'no-duplicate-case': 'error',
            'no-invalid-regexp': 'error',
            'no-unsafe-finally': 'error',
            'no-useless-return': 'error',
            'no-inline-comments': 'error',
            'no-warning-comments': 'warn',
            'no-unsafe-negation': 'error',
            'prefer-rest-params': 'error',
            'symbol-description': 'error',
            'no-implicit-globals': 'error',
            'no-unreachable-loop': 'error',
            'no-compare-neg-zero': 'error',
            'max-classes-per-file': 'error',
            'no-negated-condition': 'error',
            'no-duplicate-imports': 'error',
            'max-statements': ['error', 25],
            'no-implicit-coercion': 'error',
            'no-array-constructor': 'error',
            'no-case-declarations': 'error',
            'no-loss-of-precision': 'error',
            'no-this-before-super': 'error',
            'no-constructor-return': 'error',
            'no-constant-condition': 'error',
            'array-callback-return': 'error',
            'no-dupe-class-members': 'error',
            'no-extra-boolean-cast': 'error',
            'no-prototype-builtins': 'error',
            'grouped-accessor-pairs': 'error',
            'require-atomic-updates': 'error',
            'no-useless-constructor': 'error',
            'unicode-bom': ['error', 'never'],
            'no-irregular-whitespace': 'error',
            'no-unexpected-multiline': 'error',
            'no-useless-computed-key': 'error',
            'no-empty-character-class': 'error',
            'no-useless-backreference': 'error',
            'max-nested-callbacks': ['error', 4],
            'no-async-promise-executor': 'error',
            'no-promise-executor-return': 'error',
            'no-cond-assign': ['error', 'always'],
            'no-shadow-restricted-names': 'error',
            'no-template-curly-in-string': 'error',
            'no-unmodified-loop-condition': 'error',
            'prefer-promise-reject-errors': 'error',
            'no-misleading-character-class': 'error',
            'prefer-exponentiation-operator': 'error',
            'object-curly-spacing': ['error', 'always'],
            'no-self-assign': ['error', { props: true }],
            'one-var': ['error', { initialized: 'never' }],
            'max-statements-per-line': ['error', { max: 1 }],
            'no-param-reassign': ['error', { props: false }],
            'no-empty': ['error', { allowEmptyCatch: true }],
            'dot-notation': ['error', { allowKeywords: true }],
            'no-redeclare': ['error', { builtinGlobals: false }],
            'no-console': ['error', { allow: ['warn', 'error'] }],
            'object-curly-newline': ['error', { consistent: true }],
            'line-comment-position': ['error', { position: 'above' }],
            'valid-typeof': ['error', { requireStringLiterals: true }],
            'new-cap': ['error', { capIsNew: false, properties: false }],
            'no-unneeded-ternary': ['error', { defaultAssignment: false }],
            'prefer-destructuring': ['error', { object: true, array: false }],
            'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
            'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
            'use-isnan': ['error', { enforceForIndexOf: true, enforceForSwitchCase: true }],
            'no-unused-expressions': ['error', { allowTernary: true, allowShortCircuit: true }],
            // stylistic
            '@stylistic/object-curly-newline': ['error', { multiline: true, consistent: true }],
            // unicorn
            'unicorn/filename-case': ['error', { cases: { kebabCase: true, camelCase: true, pascalCase: true } }],
            'no-shadow': [
                'error',
                { hoist: 'functions', builtinGlobals: false },
            ],
            'prefer-const': [
                'error',
                {
                    destructuring: 'all',
                    ignoreReadBeforeAssign: true,
                },
            ],
            'no-unused-vars': [
                'error',
                {
                    caughtErrors: 'all',
                    destructuredArrayIgnorePattern: '^_',
                },
            ],
            'prefer-arrow-callback': [
                'error',
                {
                    allowUnboundThis: true,
                    allowNamedFunctions: false,
                },
            ],
            'object-shorthand': [
                'error',
                'always',
                {
                    avoidQuotes: true,
                    ignoreConstructors: false,
                },
            ],

            'no-use-before-define': [
                'error',
                {
                    classes: true,
                    variables: true,
                    functions: false,
                },
            ],
            'no-restricted-globals': [
                'error',
                { name: 'global', message: 'Use `globalThis` instead.' },
                { name: 'self', message: 'Use `globalThis` instead.' },
            ],
            'no-useless-rename': [
                'warn',
                {
                    ignoreExport: false,
                    ignoreImport: false,
                    ignoreDestructuring: false,
                },
            ],
            'no-restricted-properties': [
                'error',
                { property: '__proto__', message: 'Use `Object.getPrototypeOf` or `Object.setPrototypeOf` instead.' },
                { property: '__defineGetter__', message: 'Use `Object.defineProperty` instead.' },
                { property: '__defineSetter__', message: 'Use `Object.defineProperty` instead.' },
                { property: '__lookupGetter__', message: 'Use `Object.getOwnPropertyDescriptor` instead.' },
                { property: '__lookupSetter__', message: 'Use `Object.getOwnPropertyDescriptor` instead.' },
            ],
            'padding-line-between-statements': [
                'error',
                { next: '*', blankLine: 'always', prev: ['const', 'let', 'var'] },
                { blankLine: 'any', prev: ['const', 'let', 'var'], next: ['const', 'let', 'var'] },
                { next: '*', blankLine: 'always', prev: ['for', 'do', 'while'] },
                { prev: '*', next: 'return', blankLine: 'always' },
                { next: '*', prev: 'directive', blankLine: 'always' },
                { prev: '*', next: 'for', blankLine: 'always' },
                { next: '*', prev: 'import', blankLine: 'always' },
                { prev: 'import', next: 'import', blankLine: 'any' },
                { next: '*', prev: 'if', blankLine: 'always' },
                { next: '*', prev: 'function', blankLine: 'always' },
                { prev: '*', next: 'function', blankLine: 'always' },
                { prev: '*', next: 'export', blankLine: 'always' },
            ],
            'no-restricted-syntax': [
                'error',
                // {
                //     selector: 'SequenceExpression',
                //     message: 'The comma operator is confusing and a common mistake. Don’t use it!',
                // },
                {
                    selector: 'ForInStatement',
                    message:
                        'for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array.',
                },
                {
                    selector: 'LabeledStatement',
                    message:
                        'Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand.',
                },
                {
                    selector: 'WithStatement',
                    message:
                        '`with` is disallowed in strict mode because it makes code impossible to predict and optimize.',
                },
            ],

        },
    },
]
