const cjsExport = 'cjs-export';
const cjsImport = 'cjs-import';

module.exports = {
    'sort-vars': 'error',
    'no-undefined': 'error',
    'prefer-const': 'error',
    'no-inline-comments': 'error',
    'max-classes-per-file': 'error',
    'no-negated-condition': 'error',
    'no-duplicate-imports': 'error',
    'prefer-exponentiation-operator': 'error',
    'max-depth': ['error', 4],
    'max-params': ['error', 3],
    'max-statements': ['error', 25],
    'max-nested-callbacks': ['error', 4],
    'object-curly-spacing': ['error', 'always'],
    'new-cap': ['error', { capIsNew: false, properties: false }],
    'max-statements-per-line': ['error', { max: 1 }],
    'max-len': ['error', { code: 120, ignoreUrls: true }],
    'object-curly-newline': ['error', { consistent: true }],
    'line-comment-position': ['error', { position: 'above' }],
    'prefer-destructuring': ['error', { object: true, array: false }],
    'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
    'class-methods-use-this': ['error', { enforceForClassFields: false }],
    'no-unused-expressions': ['error', { allowShortCircuit: true, allowTernary: true }],
    'no-shadow': ['error', { builtinGlobals: false, allow: ['resolve', 'reject', 'done', 'task'] }],
    'padding-line-between-statements': [
        'error',
        { blankLine: 'always', prev: '*', next: 'return' },
        { blankLine: 'always', prev: ['const', 'let', 'var'], next: '*' },
        { blankLine: 'any', prev: ['const', 'let', 'var'], next: ['const', 'let', 'var'] },
        { blankLine: 'always', prev: 'directive', next: '*' },
        { blankLine: 'always', prev: ['for', 'do', 'while'], next: '*' },
        { blankLine: 'always', prev: '*', next: 'for' },
        { blankLine: 'always', prev: 'import', next: '*' },
        { blankLine: 'any', prev: 'import', next: 'import' },
        { blankLine: 'always', prev: 'if', next: '*' },
        { blankLine: 'always', prev: 'function', next: '*' },
        { blankLine: 'always', prev: '*', next: 'function' },
        { blankLine: 'always', prev: '*', next: 'export' },
        { blankLine: 'always', prev: '*', next: cjsExport },
        { blankLine: 'any', prev: cjsExport, next: cjsExport },
        { blankLine: 'any', prev: cjsImport, next: '*' },
        { blankLine: 'any', prev: cjsImport, next: cjsImport },
    ],
    'no-restricted-syntax': [
        'error',
        {
            selector: 'SequenceExpression',
            message: 'The comma operator is confusing and a common mistake. Don’t use it!',
        },
    ],
};
